// <auto-generated />
using System;
using Ecommerce.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ecommerce.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260903000754_AddShippingRates")]
    partial class AddShippingRates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ecommerce.Domain.Catalog.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Catalog.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Catalog.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AltText")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Catalog.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("PriceOverride")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("ProductVariants", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Inventory.InventoryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DamagedQuantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("ReturnedQuantity")
                        .HasColumnType("integer");

                    b.Property<int>("SoldQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId")
                        .IsUnique();

                    b.ToTable("Inventory", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Inventory.InventoryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("InventoryTransactions", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Commune")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("DiscountTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Fbclid")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LandingPage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Referrer")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal>("ShippingCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Ttclid")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UtmCampaign")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UtmContent")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UtmMedium")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UtmSource")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UtmTerm")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Wilaya")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("Phone");

                    b.HasIndex("UtmSource");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Orders.OrderCallAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CalledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("NextCallAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderCallAttempts", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Orders.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Orders.OrderPromotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PromotionId")
                        .HasColumnType("uuid");

                    b.Property<string>("PromotionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderPromotions", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Orders.OrderStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("OldStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderStatusHistories", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Promotions.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("BuyQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("CouponCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("FixedAmountValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("GetQuantity")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("PercentageValue")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CouponCode")
                        .IsUnique()
                        .HasFilter("\"CouponCode\" IS NOT NULL");

                    b.HasIndex("IsActive", "StartsAtUtc", "EndsAtUtc");

                    b.ToTable("Promotions", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Promotions.PromotionCategory", b =>
                {
                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("PromotionId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("PromotionCategories", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Promotions.PromotionProduct", b =>
                {
                    b.Property<Guid>("PromotionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("PromotionId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("PromotionProducts", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Shipping.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Carrier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProviderShipmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProviderStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Shipments", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Shipping.ShipmentTrackingEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NormalizedStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId");

                    b.ToTable("ShipmentTrackingEvents", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Shipping.ShippingRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HomeDeliveryPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("StopDeskPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Wilaya")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Wilaya")
                        .IsUnique();

                    b.ToTable("ShippingRates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("850fba4c-66f9-36fb-8b49-f77dea5a3aa3"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Adrar"
                        },
                        new
                        {
                            Id = new Guid("596ef71e-e2e0-1e1f-1ccd-ad11810230b3"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Chlef"
                        },
                        new
                        {
                            Id = new Guid("4dbc614d-7a52-603e-a93d-bad4b483f3b4"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Laghouat"
                        },
                        new
                        {
                            Id = new Guid("274740bf-7e89-2b24-1238-485559ed5874"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Oum El Bouaghi"
                        },
                        new
                        {
                            Id = new Guid("e9ff221b-ca2f-0058-02ce-c17bf2f6d548"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Batna"
                        },
                        new
                        {
                            Id = new Guid("f2e73d67-7f73-d62d-002d-4b789fb23bfc"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Béjaïa"
                        },
                        new
                        {
                            Id = new Guid("ebdd2f90-7106-f706-b880-44532f03adcc"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Biskra"
                        },
                        new
                        {
                            Id = new Guid("55e9b1e9-e638-1455-92da-bd8940abdfea"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Béchar"
                        },
                        new
                        {
                            Id = new Guid("ab2af003-1b94-e5af-a0a6-3c990aa8b756"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Blida"
                        },
                        new
                        {
                            Id = new Guid("5ba72ccb-63bd-5795-254e-12fb3b7d4b15"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Bouira"
                        },
                        new
                        {
                            Id = new Guid("29263efe-2c2d-b191-8ff8-798693252b86"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Tamanrasset"
                        },
                        new
                        {
                            Id = new Guid("50d0b27a-5474-c860-8773-b3c161a8ad83"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Tébessa"
                        },
                        new
                        {
                            Id = new Guid("95cf0d49-6db9-0041-8bb1-dacc6debafba"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Tlemcen"
                        },
                        new
                        {
                            Id = new Guid("2c7ff4d0-24ae-4f16-cbe9-5109393f8826"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Tiaret"
                        },
                        new
                        {
                            Id = new Guid("d5f78783-38b5-16e5-802f-b9e725bd5e6d"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Tizi Ouzou"
                        },
                        new
                        {
                            Id = new Guid("92b7717b-2f87-b9ca-6f08-00ad4021b7d8"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Alger"
                        },
                        new
                        {
                            Id = new Guid("10246243-6b88-61bf-d376-059d33a9ba3d"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Djelfa"
                        },
                        new
                        {
                            Id = new Guid("e7ecfee2-faec-0a84-6a9f-696c16361701"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Jijel"
                        },
                        new
                        {
                            Id = new Guid("7abef508-de0c-7af4-80b2-1ff73684938d"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Sétif"
                        },
                        new
                        {
                            Id = new Guid("6283095c-1d1d-e455-1d44-2d1a42d77f4a"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Saïda"
                        },
                        new
                        {
                            Id = new Guid("99c1d2cb-8219-86d5-cd19-f828b2983ed1"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Skikda"
                        },
                        new
                        {
                            Id = new Guid("1aa5ffe2-4afa-197f-76e2-34dea51eea1d"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Sidi Bel Abbès"
                        },
                        new
                        {
                            Id = new Guid("17ca516d-8d51-016d-9bb7-54ea2d8627d2"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Annaba"
                        },
                        new
                        {
                            Id = new Guid("5c61e69b-4dd2-4030-6c06-ae8256d82686"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Guelma"
                        },
                        new
                        {
                            Id = new Guid("688da81d-3683-69dd-ad95-0fdfe9431775"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Constantine"
                        },
                        new
                        {
                            Id = new Guid("26f849ae-e588-74ff-ddbe-622bc15f9028"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Médéa"
                        },
                        new
                        {
                            Id = new Guid("2a452349-7f6f-30d1-9ed2-37edc02dff34"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Mostaganem"
                        },
                        new
                        {
                            Id = new Guid("f84f9b05-f31a-f56a-ef03-4cd7361a7bf8"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "M'Sila"
                        },
                        new
                        {
                            Id = new Guid("0b12b277-5267-497a-c867-3e2e27b9d237"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Mascara"
                        },
                        new
                        {
                            Id = new Guid("1af4ec57-c924-e1c3-ab77-80e9cfa901bc"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Ouargla"
                        },
                        new
                        {
                            Id = new Guid("9f4a6791-6918-d0b5-9d38-866542ab0709"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Oran"
                        },
                        new
                        {
                            Id = new Guid("4fafe79a-cc05-b010-3b08-55ded4857beb"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "El Bayadh"
                        },
                        new
                        {
                            Id = new Guid("91e40f32-a173-88a3-ad4f-b0bc89086838"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Illizi"
                        },
                        new
                        {
                            Id = new Guid("eba2a9a3-8514-9651-940e-93957a5d20aa"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Bordj Bou Arréridj"
                        },
                        new
                        {
                            Id = new Guid("5274b4da-50a1-c9d1-ac63-8cbbb4a9e80a"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Boumerdès"
                        },
                        new
                        {
                            Id = new Guid("8f63b149-1157-a82d-3119-2bdecbbe40a5"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "El Tarf"
                        },
                        new
                        {
                            Id = new Guid("e8ed174b-be31-5e3f-171b-47a08e858833"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Tindouf"
                        },
                        new
                        {
                            Id = new Guid("5e47453f-f3cc-eefa-1345-55a04658e4c8"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Tissemsilt"
                        },
                        new
                        {
                            Id = new Guid("594d2d21-c3f7-d68f-e6bb-94a56185fa3b"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "El Oued"
                        },
                        new
                        {
                            Id = new Guid("24dbf559-0432-7241-a377-157209af87f1"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Khenchela"
                        },
                        new
                        {
                            Id = new Guid("e3fc76a4-592a-0c28-f300-a0ef05d0b4c9"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Souk Ahras"
                        },
                        new
                        {
                            Id = new Guid("b73337ac-4e98-95cc-7bd5-e5a3bd0df7c3"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Tipaza"
                        },
                        new
                        {
                            Id = new Guid("d067d54d-f1ff-b680-6abb-f23cd8dc8060"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Mila"
                        },
                        new
                        {
                            Id = new Guid("fa6ce75d-9d9a-5ef0-1bac-868252b138a0"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Aïn Defla"
                        },
                        new
                        {
                            Id = new Guid("d7fa96a2-d2e4-c73f-c1d6-47a3398d2580"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Naâma"
                        },
                        new
                        {
                            Id = new Guid("10740bdb-174b-d17f-2572-20d51bbc0cdd"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Aïn Témouchent"
                        },
                        new
                        {
                            Id = new Guid("96e8a01a-524c-d1df-512f-d69bb535ce34"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Ghardaïa"
                        },
                        new
                        {
                            Id = new Guid("ae5ce39d-86f9-1f59-58a9-4b316e29b373"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Relizane"
                        },
                        new
                        {
                            Id = new Guid("f0aeebde-548b-276d-4a28-6c552eec8bbf"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Timimoun"
                        },
                        new
                        {
                            Id = new Guid("2e377d7b-d397-ff6c-adec-a61848d8e7bc"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Bordj Badji Mokhtar"
                        },
                        new
                        {
                            Id = new Guid("438388b0-45de-bbb9-9f52-4aa01d293c95"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Ouled Djellal"
                        },
                        new
                        {
                            Id = new Guid("1d8ce0c6-7f83-a733-54ef-0289a4712e0e"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Béni Abbès"
                        },
                        new
                        {
                            Id = new Guid("0965f7ad-f55c-ddb5-aa40-99f183ff7283"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "In Salah"
                        },
                        new
                        {
                            Id = new Guid("4782964d-4241-ea37-ab11-af4ca63389d5"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "In Guezzam"
                        },
                        new
                        {
                            Id = new Guid("9bf7b360-8e5b-9752-cd28-8ef314e7565e"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Touggourt"
                        },
                        new
                        {
                            Id = new Guid("d55bb122-8dd1-5d4e-01fc-ce3453f57f87"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "Djanet"
                        },
                        new
                        {
                            Id = new Guid("5c5f0ab6-c692-b192-3576-17d53a88e64e"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "El M'Ghair"
                        },
                        new
                        {
                            Id = new Guid("ca5fdc0c-cdb7-e646-380c-df4ccc019f7f"),
                            CreatedAtUtc = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            HomeDeliveryPrice = 600m,
                            IsActive = true,
                            StopDeskPrice = 400m,
                            Wilaya = "El Meniaa"
                        });
                });

            modelBuilder.Entity("Ecommerce.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Ecommerce.Domain.Catalog.Product", b =>
                {
                    b.HasOne("Ecommerce.Domain.Catalog.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Ecommerce.Domain.Catalog.ProductImage", b =>
                {
                    b.HasOne("Ecommerce.Domain.Catalog.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ecommerce.Domain.Catalog.ProductVariant", b =>
                {
                    b.HasOne("Ecommerce.Domain.Catalog.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Ecommerce.Domain.Inventory.InventoryRecord", b =>
                {
                    b.HasOne("Ecommerce.Domain.Catalog.ProductVariant", "ProductVariant")
                        .WithOne("Inventory")
                        .HasForeignKey("Ecommerce.Domain.Inventory.InventoryRecord", "ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("Ecommerce.Domain.Inventory.InventoryTransaction", b =>
                {
                    b.HasOne("Ecommerce.Domain.Catalog.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("Ecommerce.Domain.Orders.OrderCallAttempt", b =>
                {
                    b.HasOne("Ecommerce.Domain.Orders.Order", "Order")
                        .WithMany("CallAttempts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Ecommerce.Domain.Orders.OrderItem", b =>
                {
                    b.HasOne("Ecommerce.Domain.Orders.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Ecommerce.Domain.Orders.OrderPromotion", b =>
                {
                    b.HasOne("Ecommerce.Domain.Orders.Order", "Order")
                        .WithMany("AppliedPromotions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Ecommerce.Domain.Orders.OrderStatusHistory", b =>
                {
                    b.HasOne("Ecommerce.Domain.Orders.Order", "Order")
                        .WithMany("StatusHistory")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Ecommerce.Domain.Promotions.PromotionCategory", b =>
                {
                    b.HasOne("Ecommerce.Domain.Catalog.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.Domain.Promotions.Promotion", "Promotion")
                        .WithMany("Categories")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("Ecommerce.Domain.Promotions.PromotionProduct", b =>
                {
                    b.HasOne("Ecommerce.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.Domain.Promotions.Promotion", "Promotion")
                        .WithMany("Products")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("Ecommerce.Domain.Shipping.Shipment", b =>
                {
                    b.HasOne("Ecommerce.Domain.Orders.Order", "Order")
                        .WithOne("Shipment")
                        .HasForeignKey("Ecommerce.Domain.Shipping.Shipment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Ecommerce.Domain.Shipping.ShipmentTrackingEvent", b =>
                {
                    b.HasOne("Ecommerce.Domain.Shipping.Shipment", "Shipment")
                        .WithMany("TrackingEvents")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Ecommerce.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Ecommerce.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Ecommerce.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Ecommerce.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ecommerce.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Ecommerce.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ecommerce.Domain.Catalog.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Ecommerce.Domain.Catalog.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Ecommerce.Domain.Catalog.ProductVariant", b =>
                {
                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Ecommerce.Domain.Orders.Order", b =>
                {
                    b.Navigation("AppliedPromotions");

                    b.Navigation("CallAttempts");

                    b.Navigation("Items");

                    b.Navigation("Shipment");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("Ecommerce.Domain.Promotions.Promotion", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Ecommerce.Domain.Shipping.Shipment", b =>
                {
                    b.Navigation("TrackingEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
